services:
  - type: web
    name: v2ray-mtn
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/fadil-uchiha/mtn-v2ray 
    plan: free
    envVars:
      - key: UUID
        sync: false
      - key: SNI_HOST
        value: edge-star-shv-01-lis1.facebook.com
    autoDeploy: false